// examples-registry.test.js — shape guard for the vendored example-mirror
// registry (worker/examples/, generated by scripts/vendor-examples.mjs). Runs in
// `npm test`, so the sync-examples workflow fails if vendoring produced a
// malformed registry. The deep integrity checks (replay, cross-thread) happen in
// the vendor script itself and upstream in ClisTa-Protocol; here we assert the
// generated modules are well-formed and seedable.
import test from 'node:test';
import assert from 'node:assert/strict';
import { examples } from '../worker/examples/index.js';

test("vendored example registry is well-formed and seedable", async () => {
  assert.ok(Array.isArray(examples) && examples.length >= 1, "at least one example");

  const ids = examples.map((e) => e.id);
  assert.equal(new Set(ids).size, ids.length, "example ids are unique");

  for (const ex of examples) {
    for (const field of ["id", "title", "summary", "kind", "entryThreadId", "threads"]) {
      assert.ok(ex[field], `${ex.id} missing ${field}`);
    }
    assert.ok(Array.isArray(ex.threads) && ex.threads.length >= 1, `${ex.id} has threads`);

    const threadIds = ex.threads.map((t) => t.threadId);
    assert.ok(threadIds.includes(ex.entryThreadId), `${ex.id} entryThreadId is a declared thread`);

    for (const t of ex.threads) {
      assert.ok(t.threadId && Array.isArray(t.events) && t.events.length >= 1, `${ex.id} thread ${t.threadId} has events`);
      assert.ok(t.events.every((e) => e.thread_id === t.threadId), `${ex.id}: every event belongs to ${t.threadId}`);
      assert.ok(t.events.every((e) => e.content_hash), `${ex.id}: events carry content hashes`);
    }
  }
});
