// Generated by scripts/vendor-examples.mjs — do not edit by hand.
// The cockpit's example-mirror registry, vendored from ClisTa-Protocol.
import { example as ex_pharma_phase_gate_multithreaded } from "./pharma-phase-gate-multithreaded.js";
import { example as ex_ongoing_monitoring_concept_drift } from "./ongoing-monitoring-concept-drift.js";
import { example as ex_clista_csv_cli_build } from "./clista-csv-cli-build.js";

export const examples = [
  ex_pharma_phase_gate_multithreaded,
  ex_ongoing_monitoring_concept_drift,
  ex_clista_csv_cli_build,
];
