// Generated by scripts/vendor-examples.mjs — do not edit by hand.
// The cockpit's example-mirror registry, vendored from ClisTa-Protocol.
import { example as ex_pharma_phase_gate_multithreaded } from "./pharma-phase-gate-multithreaded.js";

export const examples = [
  ex_pharma_phase_gate_multithreaded,
];
